# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HITGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('duration', models.IntegerField()),
                ('lifetime', models.IntegerField()),
                ('cost', models.FloatField()),
                ('keywords', models.CharField(max_length=250)),
                ('height', models.IntegerField(default=650)),
                ('donation', models.IntegerField(default=0)),
                ('offline', models.SmallIntegerField(default=False)),
                ('minapprovedamount', models.IntegerField(default=None)),
                ('minapprovedpercent', models.IntegerField(default=None)),
                ('countrycode', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('numaccount', models.IntegerField()),
                ('phonenum', models.IntegerField()),
                ('workexper', models.TextField()),
                ('educationback', models.TextField()),
                ('userlevel', models.IntegerField()),
                ('numuploaded', models.IntegerField()),
                ('numsubmitted', models.IntegerField(default=0)),
                ('numacceptances', models.IntegerField(default=0)),
                ('numrejections', models.IntegerField(default=0)),
                ('blocked', models.SmallIntegerField(default=False)),
                ('donatedamount', models.FloatField(default=0.0)),
                ('bonusamount', models.FloatField(default=0.0)),
                ('verified', models.SmallIntegerField(default=False)),
            ],
        ),
    ]
