# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CITIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discriminator', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitslug', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('depth', models.FloatField()),
                ('ready', models.SmallIntegerField(default=True)),
                ('published', models.SmallIntegerField(default=False)),
                ('completed', models.SmallIntegerField(default=False)),
                ('compensated', models.SmallIntegerField(default=False)),
                ('checked', models.SmallIntegerField(default=False)),
                ('accepted', models.SmallIntegerField(default=False)),
                ('validated', models.SmallIntegerField(default=False)),
                ('reason', models.TextField()),
                ('isdisputed', models.SmallIntegerField(default=False)),
                ('disputedcontent', models.TextField()),
                ('comments', models.TextField()),
                ('timeaccepted', models.DateTimeField()),
                ('timecompleted', models.DateTimeField()),
                ('timeonserver', models.DateTimeField()),
                ('ipaddress', models.CharField(max_length=15)),
                ('page', models.CharField(default='', max_length=250)),
                ('completeness', models.FloatField()),
                ('quality', models.FloatField()),
                ('donatedamount', models.FloatField(default=0.0)),
                ('bonusamount', models.FloatField(default=0.0)),
                ('useful', models.SmallIntegerField(default=True)),
                ('annodocument', models.CharField(max_length=250)),
                ('discriminator', models.CharField(max_length=250)),
                ('checker_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkhits', to='CITIS.Worker')),
                ('commenter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commandhits', to='CITIS.Worker')),
                ('groupid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CITIS.HITGroup')),
                ('worker_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workhits', to='CITIS.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='ConstantBonus',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CITIS.BonusSchedule')),
                ('amount', models.FloatField()),
            ],
            bases=('CITIS.bonusschedule',),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='hitid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CITIS.HIT'),
        ),
        migrations.AddField(
            model_name='bonusschedule',
            name='groupid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CITIS.HITGroup'),
        ),
    ]
