# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITIS', '0005_auto_20171211_1830'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worker',
            table='CITIS_users',
        ),
    ]
