# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITIS', '0008_auto_20171211_1838'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bonusschedule',
            table='CITIS_bonus_schedules',
        ),
        migrations.AlterModelTable(
            name='constantbonus',
            table='CITIS_bonus_schedule_constant',
        ),
        migrations.AlterModelTable(
            name='eventlog',
            table='CITIS_event_log',
        ),
        migrations.AlterModelTable(
            name='hitgroup',
            table='CITIS_hit_groups',
        ),
    ]
