# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITIS', '0009_auto_20171211_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitgroup',
            name='countrycode',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hitgroup',
            name='donation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hitgroup',
            name='minapprovedamount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hitgroup',
            name='minapprovedpercent',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hitgroup',
            name='offline',
            field=models.SmallIntegerField(default=False, null=True),
        ),
    ]
