# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITIS', '0010_auto_20171211_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='discriminator',
            new_name='type',
        ),
    ]
