# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITIS', '0012_auto_20171211_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='accepted',
            field=models.SmallIntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='annodocument',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='checked',
            field=models.SmallIntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='compensated',
            field=models.SmallIntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='completed',
            field=models.SmallIntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='completeness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='disputedcontent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='ipaddress',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='isdisputed',
            field=models.SmallIntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='published',
            field=models.SmallIntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='quality',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='ready',
            field=models.SmallIntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='timeaccepted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='timecompleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='timeonserver',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='useful',
            field=models.SmallIntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='validated',
            field=models.SmallIntegerField(default=False, null=True),
        ),
    ]
