# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITIS', '0014_auto_20171211_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='checker_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='commenter_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='worker_id',
            field=models.IntegerField(null=True),
        ),
    ]
