# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITIS', '0015_auto_20171211_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='groupid',
            new_name='group',
        ),
    ]
