# Generated by Django 2.0.4 on 2018-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITIS', '0017_auto_20180207_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='group',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='hitgroup_hit', to='CITIS.HITGroup'),
        ),
    ]
