# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Annoter'), (2, 'Auditor'), (3, 'Valuator')], null=True),
        ),
    ]
