# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numuploaded',
            field=models.IntegerField(default=0),
        ),
    ]
