# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_numuploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='numuploaded',
        ),
    ]
