# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_numuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('a', 'Annoter'), ('b', 'Auditor'), ('c', 'Valuator')], max_length=10, null=True),
        ),
    ]
