# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180205_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bankaccount',
            field=models.IntegerField(null=True, verbose_name='银行卡号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.IntegerField(default=0, verbose_name='是否被锁定'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bonusamount',
            field=models.FloatField(default=0, verbose_name='薪酬总计'),
        ),
        migrations.AddField(
            model_name='profile',
            name='donatedamount',
            field=models.FloatField(default=0, verbose_name='捐助数额'),
        ),
        migrations.AddField(
            model_name='profile',
            name='edubackground',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='numacceptances',
            field=models.IntegerField(default=0, verbose_name='被接收数量'),
        ),
        migrations.AddField(
            model_name='profile',
            name='numrejections',
            field=models.IntegerField(default=0, verbose_name='被拒绝数量'),
        ),
        migrations.AddField(
            model_name='profile',
            name='numsubmitted',
            field=models.IntegerField(default=0, verbose_name='已完成数量'),
        ),
        migrations.AddField(
            model_name='profile',
            name='numuploaded',
            field=models.IntegerField(default=0, null=True, verbose_name='上传视频数量'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='userlevel',
            field=models.IntegerField(null=True, verbose_name='用户等级1,2,3...'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.IntegerField(default=0, verbose_name='是否被认证'),
        ),
        migrations.AddField(
            model_name='profile',
            name='workexper',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Annoter', 'Annoter'), ('Auditor', 'Auditor'), ('Valuator', 'Valuator')], max_length=10, null=True),
        ),
    ]
