# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180205_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='edubackground',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('worker', 'worker'), ('other', 'other')], max_length=30),
        ),
    ]
