# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180205_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bankaccount',
            field=models.CharField(max_length=40, null=True, verbose_name='银行卡号'),
        ),
    ]
