# Generated by Django 2.0.4 on 2018-04-18 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CITIS_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utype', models.CharField(choices=[('Annoter', '标注员'), ('Auditor', '审计员'), ('Valuator', '评议员')], default=2, max_length=10, verbose_name='身份')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='地址')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('a', '女'), ('b', '男')], max_length=10, null=True, verbose_name='性别')),
                ('numaccount', models.CharField(max_length=17, null=True, verbose_name='银行卡号')),
                ('phonenum', models.CharField(max_length=11, null=True, verbose_name='电话号码')),
                ('workexper', models.TextField(blank=True)),
                ('educationback', models.CharField(choices=[('a', '在校学生'), ('b', '已工作者'), ('c', '其他')], max_length=10, null=True, verbose_name='教育背景')),
                ('userlevel', models.IntegerField(null=True, verbose_name='用户等级1,2,3...')),
                ('numuploaded', models.IntegerField(default=0, null=True, verbose_name='上传视频数量')),
                ('numsubmitted', models.IntegerField(default=0, verbose_name='已完成数量')),
                ('numacceptances', models.IntegerField(default=0, verbose_name='被接收数量')),
                ('numrejections', models.IntegerField(default=0, verbose_name='被拒绝数量')),
                ('blocked', models.IntegerField(default=0, verbose_name='是否被锁定')),
                ('bonusamount', models.FloatField(default=0, verbose_name='薪酬总计')),
                ('verified', models.IntegerField(default=0, verbose_name='是否被认证')),
                ('donatedamount', models.FloatField(default=0, verbose_name='捐助数额')),
                ('authuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'email_verify_records',
            },
        ),
    ]
