# Generated by Django 2.0.4 on 2018-04-18 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'attributes',
            },
        ),
        migrations.CreateModel(
            name='AttributeAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField()),
                ('value', models.SmallIntegerField(default=False)),
                ('attribute', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='AttrAnno_Attr', to='video_tasks.Attribute')),
            ],
            options={
                'db_table': 'attribute_annotations',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtl', models.IntegerField()),
                ('ytl', models.IntegerField()),
                ('xbr', models.IntegerField()),
                ('ybr', models.IntegerField()),
                ('frame', models.IntegerField()),
                ('occluded', models.SmallIntegerField(default=False)),
                ('outside', models.SmallIntegerField(default=False)),
                ('isrevised', models.SmallIntegerField(default=False)),
            ],
            options={
                'db_table': 'boxes',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istraining', models.SmallIntegerField(default=0, null=True)),
                ('status', models.IntegerField(default=0)),
                ('auditor_id', models.IntegerField(default=-1)),
                ('valuator_id', models.IntegerField(default=-1)),
                ('evaluate', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='path_job', to='video_tasks.Job')),
                ('label', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='path_label', to='video_tasks.Label')),
            ],
            options={
                'db_table': 'paths',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(null=True)),
                ('stop', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'segments',
            },
        ),
        migrations.CreateModel(
            name='User_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=-1)),
                ('appeal', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_user_records', to='video_tasks.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_records',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=250, null=True)),
                ('uploaderid', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('totalframes', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('skip', models.IntegerField(default=0)),
                ('perobjectbonus', models.FloatField(default=0, null=True)),
                ('completionbonus', models.FloatField(default=0, null=True)),
                ('isfortraining', models.SmallIntegerField(default=0, null=True)),
                ('trainvalidator', models.TextField(blank=True, null=True)),
                ('blowradius', models.IntegerField(default=0, null=True)),
                ('scene', models.CharField(max_length=50, null=True)),
                ('resolutionx', models.IntegerField(null=True)),
                ('resolutiony', models.IntegerField(null=True)),
                ('videoannodocument', models.CharField(max_length=250, null=True)),
                ('type', models.CharField(max_length=40, null=True)),
                ('publish', models.IntegerField(default=0)),
                ('applied_id', models.IntegerField(default=-1)),
                ('auditor_id', models.IntegerField(default=-1)),
                ('valuator_id', models.IntegerField(default=-1)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_video', to='video_tasks.Video'),
        ),
        migrations.AddField(
            model_name='label',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_label', to='video_tasks.Video'),
        ),
        migrations.AddField(
            model_name='job',
            name='segment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video_tasks.Segment'),
        ),
        migrations.AddField(
            model_name='box',
            name='pathid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_path', to='video_tasks.Path'),
        ),
        migrations.AddField(
            model_name='attributeannotation',
            name='path',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='AttrAnno_Path', to='video_tasks.Path'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_attribute', to='video_tasks.Label'),
        ),
    ]
