# Generated by Django 2.0.4 on 2018-04-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='desc',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
