# Generated by Django 2.0.4 on 2018-04-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_tasks', '0002_video_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='desc',
            new_name='description',
        ),
    ]
